import type { ObjectTableRecord } from "./object-table-config"

export const exampleCompanyRecords: ObjectTableRecord[] = [
  {
    id: "northwind",
    logo: null,
    name: "Northwind Traders",
    lifecycleStage: "customer",
    domain: "northwind.example",
    website: "https://northwind.example",
    industry: "Distribution",
    categories: ["B2B", "Distribution", "Logistics", "Enterprise"],
    linkedIn: "https://linkedin.com/company/northwind-traders",
    description:
      "Northwind Traders coordinates a global network of specialty food suppliers, distributors, and regional customers from one shared operating model.",
    employeeCount: 12_480,
    foundedOn: "1994-04-12",
    lastReviewedAt: "2026-08-21T16:42:00.000Z",
    strategic: true,
    contactEmail: "partnerships@northwind.example",
    contactPhone: "+12065550142",
  },
  {
    id: "contoso",
    logo: null,
    name: "Contoso",
    lifecycleStage: "customer",
    domain: "contoso.example",
    website: "https://contoso.example",
    industry: "Manufacturing",
    categories: ["B2B", "Manufacturing"],
    linkedIn: "https://linkedin.com/company/contoso",
    description:
      "Contoso manufactures and distributes consumer electronics through international retail and partner channels.",
    employeeCount: 4_064,
    foundedOn: "2001-09-18",
    lastReviewedAt: "2026-08-18T20:15:00.000Z",
    strategic: false,
    contactEmail: "hello@contoso.example",
    contactPhone: "+14255550188",
  },
  {
    id: "fabrikam",
    logo: { assetId: "missing-logo", alt: "Fabrikam logo" },
    name: "Fabrikam",
    lifecycleStage: "prospect",
    domain: "fabrikam.example",
    website: "https://fabrikam.example",
    industry: "Industrial technology",
    categories: ["B2B", "Industrial technology", "Enterprise"],
    linkedIn: "https://linkedin.com/company/fabrikam",
    description:
      "Fabrikam develops industrial automation systems for complex manufacturing environments.",
    employeeCount: 256,
    foundedOn: "2012-02-29",
    lastReviewedAt: "2026-08-03T09:30:00.000Z",
    strategic: true,
    contactEmail: "sales@fabrikam.example",
    contactPhone: "+13125550164",
  },
  {
    id: "adventure-works",
    logo: null,
    name: "Adventure Works",
    lifecycleStage: "customer",
    domain: "adventure-works.example",
    website: "https://adventure-works.example",
    industry: "Consumer goods",
    categories: ["B2C", "Consumer goods", "Retail"],
    linkedIn: "https://linkedin.com/company/adventure-works",
    description:
      "Adventure Works designs outdoor equipment and serves customers through stores, distributors, and direct commerce.",
    employeeCount: 1_704,
    foundedOn: "1998-06-05",
    lastReviewedAt: "2026-07-29T18:05:00.000Z",
    strategic: false,
    contactEmail: "team@adventure-works.example",
    contactPhone: "+13035550196",
  },
  {
    id: "tailspin-toys",
    logo: null,
    name: "Tailspin Toys",
    lifecycleStage: "prospect",
    domain: "tailspintoys.example",
    website: "https://tailspintoys.example",
    industry: "Retail",
  },
  {
    id: "woodgrove-bank",
    logo: null,
    name: "Woodgrove Bank",
    lifecycleStage: "customer",
    domain: "woodgrovebank.example",
    website: "https://woodgrovebank.example",
    industry: "Financial services",
  },
  {
    id: "litware",
    logo: null,
    name: "Litware",
    lifecycleStage: "inactive",
    domain: "litware.example",
    website: "https://litware.example",
    industry: "Software",
  },
  {
    id: "proseware",
    logo: null,
    name: "Proseware",
    lifecycleStage: "prospect",
    domain: "proseware.example",
    website: "https://proseware.example",
    industry: "Professional services",
  },
  {
    id: "coho-winery",
    logo: null,
    name: "Coho Winery",
    lifecycleStage: "customer",
    domain: "cohowinery.example",
    website: "https://cohowinery.example",
    industry: "Food and beverage",
  },
  {
    id: "trey-research",
    logo: null,
    name: "Trey Research",
    lifecycleStage: "prospect",
    domain: "treyresearch.example",
    website: "https://treyresearch.example",
    industry: "Research",
  },
  {
    id: "a-datum",
    logo: null,
    name: "A. Datum",
    lifecycleStage: "inactive",
    domain: "adatum.example",
    website: "https://adatum.example",
    industry: "Data services",
  },
  {
    id: "blue-yonder",
    logo: null,
    name: "Blue Yonder Airlines",
    lifecycleStage: "prospect",
    domain: "blueyonder.example",
    website: "https://blueyonder.example",
    industry: "Transportation",
  },
]
