import { readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"

import { Storage } from "@/server/database/schema"

const target = fileURLToPath(
  new URL("./drizzle-schema.generated.ts", import.meta.url)
)
const lines = [
  "// Generated by pnpm db:generate. Do not edit.",
  'import { Storage, identityBindings, assetBlobs, assetReferences, eventJournal, eventJournalState, recordSearch, searchIndexState } from "@/server/database/schema"',
  "export const identityBindingTable = identityBindings",
  "export const blobTable = assetBlobs",
  "export const assetReferenceTable = assetReferences",
  "export const eventJournalTable = eventJournal",
  "export const eventJournalStateTable = eventJournalState",
  "export const recordSearchTable = recordSearch",
  "export const searchIndexStateTable = searchIndexState",
]
for (const group of ["core", "interfaces", "objects", "linkTables"] as const) {
  for (const key of Object.keys(Storage[group]).sort())
    lines.push(`export const ${group}_${key} = Storage.${group}.${key}`)
}
const content = `${lines.join("\n")}\n`
if (process.argv.includes("--check")) {
  if (readFileSync(target, "utf8") !== content)
    throw new Error(
      "Storage exports changed. Run pnpm --filter company-os db:generate and review the migration."
    )
} else writeFileSync(target, content)
