import type { ObjectTableRecord } from "./object-table-config"

export const exampleCompanyRecords: ObjectTableRecord[] = [
  {
    id: "northwind",
    logo: null,
    name: "Northwind Traders",
    lifecycleStage: "customer",
    domain: "northwind.example",
    website: "https://northwind.example",
    industry: "Distribution",
  },
  {
    id: "contoso",
    logo: null,
    name: "Contoso",
    lifecycleStage: "customer",
    domain: "contoso.example",
    website: "https://contoso.example",
    industry: "Manufacturing",
  },
  {
    id: "fabrikam",
    logo: null,
    name: "Fabrikam",
    lifecycleStage: "prospect",
    domain: "fabrikam.example",
    website: "https://fabrikam.example",
    industry: "Industrial technology",
  },
  {
    id: "adventure-works",
    logo: null,
    name: "Adventure Works",
    lifecycleStage: "customer",
    domain: "adventure-works.example",
    website: "https://adventure-works.example",
    industry: "Consumer goods",
  },
  {
    id: "tailspin-toys",
    logo: null,
    name: "Tailspin Toys",
    lifecycleStage: "prospect",
    domain: "tailspintoys.example",
    website: "https://tailspintoys.example",
    industry: "Retail",
  },
  {
    id: "woodgrove-bank",
    logo: null,
    name: "Woodgrove Bank",
    lifecycleStage: "customer",
    domain: "woodgrovebank.example",
    website: "https://woodgrovebank.example",
    industry: "Financial services",
  },
  {
    id: "litware",
    logo: null,
    name: "Litware",
    lifecycleStage: "inactive",
    domain: "litware.example",
    website: "https://litware.example",
    industry: "Software",
  },
  {
    id: "proseware",
    logo: null,
    name: "Proseware",
    lifecycleStage: "prospect",
    domain: "proseware.example",
    website: "https://proseware.example",
    industry: "Professional services",
  },
  {
    id: "coho-winery",
    logo: null,
    name: "Coho Winery",
    lifecycleStage: "customer",
    domain: "cohowinery.example",
    website: "https://cohowinery.example",
    industry: "Food and beverage",
  },
  {
    id: "trey-research",
    logo: null,
    name: "Trey Research",
    lifecycleStage: "prospect",
    domain: "treyresearch.example",
    website: "https://treyresearch.example",
    industry: "Research",
  },
  {
    id: "a-datum",
    logo: null,
    name: "A. Datum",
    lifecycleStage: "inactive",
    domain: "adatum.example",
    website: "https://adatum.example",
    industry: "Data services",
  },
  {
    id: "blue-yonder",
    logo: null,
    name: "Blue Yonder Airlines",
    lifecycleStage: "prospect",
    domain: "blueyonder.example",
    website: "https://blueyonder.example",
    industry: "Transportation",
  },
]
