CREATE INDEX "activities_search_idx" ON "activities" USING gin ((setweight(to_tsvector('simple', coalesce("title", '')), 'A') || setweight(to_tsvector('simple', coalesce("outcome", '')), 'B')));--> statement-breakpoint
CREATE INDEX "assets_search_idx" ON "assets" USING gin ((setweight(to_tsvector('simple', coalesce("name", '')), 'A')));--> statement-breakpoint
CREATE INDEX "campaigns_search_idx" ON "campaigns" USING gin ((setweight(to_tsvector('simple', coalesce("name", '')), 'A') || setweight(to_tsvector('simple', coalesce("objective", '')), 'B')));--> statement-breakpoint
CREATE INDEX "companies_search_idx" ON "companies" USING gin ((setweight(to_tsvector('simple', coalesce("name", '')), 'A') || setweight(to_tsvector('simple', coalesce("website", '')), 'B')));--> statement-breakpoint
CREATE INDEX "contacts_search_idx" ON "contacts" USING gin ((setweight(to_tsvector('simple', coalesce("name", '')), 'A') || setweight(to_tsvector('simple', coalesce("email", '')), 'B') || setweight(to_tsvector('simple', coalesce("job_title", '')), 'B') || setweight(to_tsvector('simple', coalesce("phone", '')), 'B')));--> statement-breakpoint
CREATE INDEX "contents_search_idx" ON "contents" USING gin ((setweight(to_tsvector('simple', coalesce("title", '')), 'A') || setweight(to_tsvector('simple', coalesce("brief", '')), 'B') || setweight(to_tsvector('simple', coalesce("body", '')), 'B')));--> statement-breakpoint
CREATE INDEX "deals_search_idx" ON "deals" USING gin ((setweight(to_tsvector('simple', coalesce("name", '')), 'A') || setweight(to_tsvector('simple', coalesce("next_step", '')), 'B')));--> statement-breakpoint
CREATE INDEX "enrollments_search_idx" ON "enrollments" USING gin ((setweight(to_tsvector('simple', coalesce("name", '')), 'A') || setweight(to_tsvector('simple', coalesce("context", '')), 'B')));--> statement-breakpoint
CREATE INDEX "issues_search_idx" ON "issues" USING gin ((setweight(to_tsvector('simple', coalesce("title", '')), 'A') || setweight(to_tsvector('simple', coalesce("description", '')), 'B')));--> statement-breakpoint
CREATE INDEX "leads_search_idx" ON "leads" USING gin ((setweight(to_tsvector('simple', coalesce("name", '')), 'A') || setweight(to_tsvector('simple', coalesce("company_name", '')), 'B') || setweight(to_tsvector('simple', coalesce("email", '')), 'B') || setweight(to_tsvector('simple', coalesce("phone", '')), 'B')));--> statement-breakpoint
CREATE INDEX "line_items_search_idx" ON "line_items" USING gin ((setweight(to_tsvector('simple', coalesce("name", '')), 'A')));--> statement-breakpoint
CREATE INDEX "notes_search_idx" ON "notes" USING gin ((setweight(to_tsvector('simple', coalesce("content", '')), 'A')));--> statement-breakpoint
CREATE INDEX "outreaches_search_idx" ON "outreaches" USING gin ((setweight(to_tsvector('simple', coalesce("subject", '')), 'A') || setweight(to_tsvector('simple', coalesce("body", '')), 'B')));--> statement-breakpoint
CREATE INDEX "projects_search_idx" ON "projects" USING gin ((setweight(to_tsvector('simple', coalesce("name", '')), 'A') || setweight(to_tsvector('simple', coalesce("objective", '')), 'B')));--> statement-breakpoint
CREATE INDEX "pull_requests_search_idx" ON "pull_requests" USING gin ((setweight(to_tsvector('simple', coalesce("title", '')), 'A') || setweight(to_tsvector('simple', coalesce("url", '')), 'B') || setweight(to_tsvector('simple', coalesce("head_commit", '')), 'B')));--> statement-breakpoint
CREATE INDEX "replies_search_idx" ON "replies" USING gin ((setweight(to_tsvector('simple', coalesce("subject", '')), 'A') || setweight(to_tsvector('simple', coalesce("body", '')), 'B') || setweight(to_tsvector('simple', coalesce("external_id", '')), 'B')));--> statement-breakpoint
CREATE INDEX "repositories_search_idx" ON "repositories" USING gin ((setweight(to_tsvector('simple', coalesce("name", '')), 'A') || setweight(to_tsvector('simple', coalesce("url", '')), 'B')));--> statement-breakpoint
CREATE INDEX "tickets_search_idx" ON "tickets" USING gin ((setweight(to_tsvector('simple', coalesce("subject", '')), 'A') || setweight(to_tsvector('simple', coalesce("description", '')), 'B') || setweight(to_tsvector('simple', coalesce("resolution", '')), 'B') || setweight(to_tsvector('simple', coalesce("external_id", '')), 'B')));