/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignOutRouteImport } from './routes/sign-out'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthLocalSessionRouteImport } from './routes/auth/local-session'
import { Route as ApiOpenapiRouteImport } from './routes/api/openapi'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiDescriptionRouteImport } from './routes/api/description'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route'
import { Route as AppDeveloperRouteRouteImport } from './routes/_app/developer/route'
import { Route as AppSalesRouteRouteImport } from './routes/_app/_sales/route'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppDeveloperIndexRouteImport } from './routes/_app/developer/index'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as AppSettingsProfileRouteImport } from './routes/_app/settings/profile'
import { Route as AppSettingsAppearanceRouteImport } from './routes/_app/settings/appearance'
import { Route as AppDeveloperSdkRouteImport } from './routes/_app/developer/sdk'
import { Route as AppDeveloperModelRouteImport } from './routes/_app/developer/model'
import { Route as AppDeveloperMcpRouteImport } from './routes/_app/developer/mcp'
import { Route as AppDeveloperApiRouteImport } from './routes/_app/developer/api'
import { Route as AppSalesLineItemsRouteImport } from './routes/_app/_sales/line-items'
import { Route as AppDeveloperDesignSystemRouteRouteImport } from './routes/_app/developer/design-system/route'
import { Route as AppSalesNotesRouteRouteImport } from './routes/_app/_sales/notes/route'
import { Route as AppSalesLeadsRouteRouteImport } from './routes/_app/_sales/leads/route'
import { Route as AppSalesDealsRouteRouteImport } from './routes/_app/_sales/deals/route'
import { Route as AppSalesContactsRouteRouteImport } from './routes/_app/_sales/contacts/route'
import { Route as AppSalesCompaniesRouteRouteImport } from './routes/_app/_sales/companies/route'
import { Route as AppDeveloperDesignSystemIndexRouteImport } from './routes/_app/developer/design-system/index'
import { Route as AppSalesNotesIndexRouteImport } from './routes/_app/_sales/notes/index'
import { Route as AppSalesLeadsIndexRouteImport } from './routes/_app/_sales/leads/index'
import { Route as AppSalesDealsIndexRouteImport } from './routes/_app/_sales/deals/index'
import { Route as AppSalesContactsIndexRouteImport } from './routes/_app/_sales/contacts/index'
import { Route as AppSalesCompaniesIndexRouteImport } from './routes/_app/_sales/companies/index'
import { Route as AppSettingsaccessUsersRouteImport } from './routes/_app/settings/(access)/users'
import { Route as AppSettingsaccessServiceAccountsRouteImport } from './routes/_app/settings/(access)/service-accounts'
import { Route as AppSettingsaccessRolesRouteImport } from './routes/_app/settings/(access)/roles'
import { Route as AppSettingsaccessRoleAssignmentsRouteImport } from './routes/_app/settings/(access)/role-assignments'
import { Route as AppSettingsaccessGroupsRouteImport } from './routes/_app/settings/(access)/groups'
import { Route as AppSettingsaccessGroupMembershipsRouteImport } from './routes/_app/settings/(access)/group-memberships'
import { Route as AppDeveloperDesignSystemFoundationsRouteImport } from './routes/_app/developer/design-system/foundations'
import { Route as AppSalesNotesRecordIdRouteImport } from './routes/_app/_sales/notes/$recordId'
import { Route as AppSalesLeadsRecordIdRouteImport } from './routes/_app/_sales/leads/$recordId'
import { Route as AppSalesDealsRecordIdRouteImport } from './routes/_app/_sales/deals/$recordId'
import { Route as AppSalesContactsRecordIdRouteImport } from './routes/_app/_sales/contacts/$recordId'
import { Route as AppSalesCompaniesRecordIdRouteImport } from './routes/_app/_sales/companies/$recordId'
import { Route as AppDeveloperDesignSystemPatternsObjectTableRouteImport } from './routes/_app/developer/design-system/patterns/object-table'
import { Route as AppDeveloperDesignSystemComponentsComponentIdRouteRouteImport } from './routes/_app/developer/design-system/components/$componentId/route'

const SignOutRoute = SignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthLocalSessionRoute = AuthLocalSessionRouteImport.update({
  id: '/auth/local-session',
  path: '/auth/local-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiRoute = ApiOpenapiRouteImport.update({
  id: '/api/openapi',
  path: '/api/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDescriptionRoute = ApiDescriptionRouteImport.update({
  id: '/api/description',
  path: '/api/description',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDeveloperRouteRoute = AppDeveloperRouteRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSalesRouteRoute = AppSalesRouteRouteImport.update({
  id: '/_sales',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppDeveloperIndexRoute = AppDeveloperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDeveloperRouteRoute,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppDeveloperSdkRoute = AppDeveloperSdkRouteImport.update({
  id: '/sdk',
  path: '/sdk',
  getParentRoute: () => AppDeveloperRouteRoute,
} as any)
const AppDeveloperModelRoute = AppDeveloperModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => AppDeveloperRouteRoute,
} as any)
const AppDeveloperMcpRoute = AppDeveloperMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AppDeveloperRouteRoute,
} as any)
const AppDeveloperApiRoute = AppDeveloperApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AppDeveloperRouteRoute,
} as any)
const AppSalesLineItemsRoute = AppSalesLineItemsRouteImport.update({
  id: '/line-items',
  path: '/line-items',
  getParentRoute: () => AppSalesRouteRoute,
} as any)
const AppDeveloperDesignSystemRouteRoute =
  AppDeveloperDesignSystemRouteRouteImport.update({
    id: '/design-system',
    path: '/design-system',
    getParentRoute: () => AppDeveloperRouteRoute,
  } as any)
const AppSalesNotesRouteRoute = AppSalesNotesRouteRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppSalesRouteRoute,
} as any)
const AppSalesLeadsRouteRoute = AppSalesLeadsRouteRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppSalesRouteRoute,
} as any)
const AppSalesDealsRouteRoute = AppSalesDealsRouteRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AppSalesRouteRoute,
} as any)
const AppSalesContactsRouteRoute = AppSalesContactsRouteRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppSalesRouteRoute,
} as any)
const AppSalesCompaniesRouteRoute = AppSalesCompaniesRouteRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppSalesRouteRoute,
} as any)
const AppDeveloperDesignSystemIndexRoute =
  AppDeveloperDesignSystemIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppDeveloperDesignSystemRouteRoute,
  } as any)
const AppSalesNotesIndexRoute = AppSalesNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSalesNotesRouteRoute,
} as any)
const AppSalesLeadsIndexRoute = AppSalesLeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSalesLeadsRouteRoute,
} as any)
const AppSalesDealsIndexRoute = AppSalesDealsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSalesDealsRouteRoute,
} as any)
const AppSalesContactsIndexRoute = AppSalesContactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSalesContactsRouteRoute,
} as any)
const AppSalesCompaniesIndexRoute = AppSalesCompaniesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSalesCompaniesRouteRoute,
} as any)
const AppSettingsaccessUsersRoute = AppSettingsaccessUsersRouteImport.update({
  id: '/(access)/users',
  path: '/users',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsaccessServiceAccountsRoute =
  AppSettingsaccessServiceAccountsRouteImport.update({
    id: '/(access)/service-accounts',
    path: '/service-accounts',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppSettingsaccessRolesRoute = AppSettingsaccessRolesRouteImport.update({
  id: '/(access)/roles',
  path: '/roles',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsaccessRoleAssignmentsRoute =
  AppSettingsaccessRoleAssignmentsRouteImport.update({
    id: '/(access)/role-assignments',
    path: '/role-assignments',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppSettingsaccessGroupsRoute = AppSettingsaccessGroupsRouteImport.update({
  id: '/(access)/groups',
  path: '/groups',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsaccessGroupMembershipsRoute =
  AppSettingsaccessGroupMembershipsRouteImport.update({
    id: '/(access)/group-memberships',
    path: '/group-memberships',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppDeveloperDesignSystemFoundationsRoute =
  AppDeveloperDesignSystemFoundationsRouteImport.update({
    id: '/foundations',
    path: '/foundations',
    getParentRoute: () => AppDeveloperDesignSystemRouteRoute,
  } as any)
const AppSalesNotesRecordIdRoute = AppSalesNotesRecordIdRouteImport.update({
  id: '/$recordId',
  path: '/$recordId',
  getParentRoute: () => AppSalesNotesRouteRoute,
} as any)
const AppSalesLeadsRecordIdRoute = AppSalesLeadsRecordIdRouteImport.update({
  id: '/$recordId',
  path: '/$recordId',
  getParentRoute: () => AppSalesLeadsRouteRoute,
} as any)
const AppSalesDealsRecordIdRoute = AppSalesDealsRecordIdRouteImport.update({
  id: '/$recordId',
  path: '/$recordId',
  getParentRoute: () => AppSalesDealsRouteRoute,
} as any)
const AppSalesContactsRecordIdRoute =
  AppSalesContactsRecordIdRouteImport.update({
    id: '/$recordId',
    path: '/$recordId',
    getParentRoute: () => AppSalesContactsRouteRoute,
  } as any)
const AppSalesCompaniesRecordIdRoute =
  AppSalesCompaniesRecordIdRouteImport.update({
    id: '/$recordId',
    path: '/$recordId',
    getParentRoute: () => AppSalesCompaniesRouteRoute,
  } as any)
const AppDeveloperDesignSystemPatternsObjectTableRoute =
  AppDeveloperDesignSystemPatternsObjectTableRouteImport.update({
    id: '/patterns/object-table',
    path: '/patterns/object-table',
    getParentRoute: () => AppDeveloperDesignSystemRouteRoute,
  } as any)
const AppDeveloperDesignSystemComponentsComponentIdRouteRoute =
  AppDeveloperDesignSystemComponentsComponentIdRouteRouteImport.update({
    id: '/components/$componentId',
    path: '/components/$componentId',
    getParentRoute: () => AppDeveloperDesignSystemRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/health': typeof HealthRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/developer': typeof AppDeveloperRouteRouteWithChildren
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/api/description': typeof ApiDescriptionRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/auth/local-session': typeof AuthLocalSessionRoute
  '/companies': typeof AppSalesCompaniesRouteRouteWithChildren
  '/contacts': typeof AppSalesContactsRouteRouteWithChildren
  '/deals': typeof AppSalesDealsRouteRouteWithChildren
  '/leads': typeof AppSalesLeadsRouteRouteWithChildren
  '/notes': typeof AppSalesNotesRouteRouteWithChildren
  '/developer/design-system': typeof AppDeveloperDesignSystemRouteRouteWithChildren
  '/line-items': typeof AppSalesLineItemsRoute
  '/developer/api': typeof AppDeveloperApiRoute
  '/developer/mcp': typeof AppDeveloperMcpRoute
  '/developer/model': typeof AppDeveloperModelRoute
  '/developer/sdk': typeof AppDeveloperSdkRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/developer/': typeof AppDeveloperIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/companies/$recordId': typeof AppSalesCompaniesRecordIdRoute
  '/contacts/$recordId': typeof AppSalesContactsRecordIdRoute
  '/deals/$recordId': typeof AppSalesDealsRecordIdRoute
  '/leads/$recordId': typeof AppSalesLeadsRecordIdRoute
  '/notes/$recordId': typeof AppSalesNotesRecordIdRoute
  '/developer/design-system/foundations': typeof AppDeveloperDesignSystemFoundationsRoute
  '/settings/group-memberships': typeof AppSettingsaccessGroupMembershipsRoute
  '/settings/groups': typeof AppSettingsaccessGroupsRoute
  '/settings/role-assignments': typeof AppSettingsaccessRoleAssignmentsRoute
  '/settings/roles': typeof AppSettingsaccessRolesRoute
  '/settings/service-accounts': typeof AppSettingsaccessServiceAccountsRoute
  '/settings/users': typeof AppSettingsaccessUsersRoute
  '/companies/': typeof AppSalesCompaniesIndexRoute
  '/contacts/': typeof AppSalesContactsIndexRoute
  '/deals/': typeof AppSalesDealsIndexRoute
  '/leads/': typeof AppSalesLeadsIndexRoute
  '/notes/': typeof AppSalesNotesIndexRoute
  '/developer/design-system/': typeof AppDeveloperDesignSystemIndexRoute
  '/developer/design-system/components/$componentId': typeof AppDeveloperDesignSystemComponentsComponentIdRouteRoute
  '/developer/design-system/patterns/object-table': typeof AppDeveloperDesignSystemPatternsObjectTableRoute
}
export interface FileRoutesByTo {
  '/access-denied': typeof AccessDeniedRoute
  '/health': typeof HealthRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/': typeof AppIndexRoute
  '/api/description': typeof ApiDescriptionRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/auth/local-session': typeof AuthLocalSessionRoute
  '/line-items': typeof AppSalesLineItemsRoute
  '/developer/api': typeof AppDeveloperApiRoute
  '/developer/mcp': typeof AppDeveloperMcpRoute
  '/developer/model': typeof AppDeveloperModelRoute
  '/developer/sdk': typeof AppDeveloperSdkRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/developer': typeof AppDeveloperIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/companies/$recordId': typeof AppSalesCompaniesRecordIdRoute
  '/contacts/$recordId': typeof AppSalesContactsRecordIdRoute
  '/deals/$recordId': typeof AppSalesDealsRecordIdRoute
  '/leads/$recordId': typeof AppSalesLeadsRecordIdRoute
  '/notes/$recordId': typeof AppSalesNotesRecordIdRoute
  '/developer/design-system/foundations': typeof AppDeveloperDesignSystemFoundationsRoute
  '/settings/group-memberships': typeof AppSettingsaccessGroupMembershipsRoute
  '/settings/groups': typeof AppSettingsaccessGroupsRoute
  '/settings/role-assignments': typeof AppSettingsaccessRoleAssignmentsRoute
  '/settings/roles': typeof AppSettingsaccessRolesRoute
  '/settings/service-accounts': typeof AppSettingsaccessServiceAccountsRoute
  '/settings/users': typeof AppSettingsaccessUsersRoute
  '/companies': typeof AppSalesCompaniesIndexRoute
  '/contacts': typeof AppSalesContactsIndexRoute
  '/deals': typeof AppSalesDealsIndexRoute
  '/leads': typeof AppSalesLeadsIndexRoute
  '/notes': typeof AppSalesNotesIndexRoute
  '/developer/design-system': typeof AppDeveloperDesignSystemIndexRoute
  '/developer/design-system/components/$componentId': typeof AppDeveloperDesignSystemComponentsComponentIdRouteRoute
  '/developer/design-system/patterns/object-table': typeof AppDeveloperDesignSystemPatternsObjectTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/health': typeof HealthRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/_app/_sales': typeof AppSalesRouteRouteWithChildren
  '/_app/developer': typeof AppDeveloperRouteRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteRouteWithChildren
  '/api/description': typeof ApiDescriptionRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/auth/local-session': typeof AuthLocalSessionRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_sales/companies': typeof AppSalesCompaniesRouteRouteWithChildren
  '/_app/_sales/contacts': typeof AppSalesContactsRouteRouteWithChildren
  '/_app/_sales/deals': typeof AppSalesDealsRouteRouteWithChildren
  '/_app/_sales/leads': typeof AppSalesLeadsRouteRouteWithChildren
  '/_app/_sales/notes': typeof AppSalesNotesRouteRouteWithChildren
  '/_app/developer/design-system': typeof AppDeveloperDesignSystemRouteRouteWithChildren
  '/_app/_sales/line-items': typeof AppSalesLineItemsRoute
  '/_app/developer/api': typeof AppDeveloperApiRoute
  '/_app/developer/mcp': typeof AppDeveloperMcpRoute
  '/_app/developer/model': typeof AppDeveloperModelRoute
  '/_app/developer/sdk': typeof AppDeveloperSdkRoute
  '/_app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/_app/developer/': typeof AppDeveloperIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/_sales/companies/$recordId': typeof AppSalesCompaniesRecordIdRoute
  '/_app/_sales/contacts/$recordId': typeof AppSalesContactsRecordIdRoute
  '/_app/_sales/deals/$recordId': typeof AppSalesDealsRecordIdRoute
  '/_app/_sales/leads/$recordId': typeof AppSalesLeadsRecordIdRoute
  '/_app/_sales/notes/$recordId': typeof AppSalesNotesRecordIdRoute
  '/_app/developer/design-system/foundations': typeof AppDeveloperDesignSystemFoundationsRoute
  '/_app/settings/(access)/group-memberships': typeof AppSettingsaccessGroupMembershipsRoute
  '/_app/settings/(access)/groups': typeof AppSettingsaccessGroupsRoute
  '/_app/settings/(access)/role-assignments': typeof AppSettingsaccessRoleAssignmentsRoute
  '/_app/settings/(access)/roles': typeof AppSettingsaccessRolesRoute
  '/_app/settings/(access)/service-accounts': typeof AppSettingsaccessServiceAccountsRoute
  '/_app/settings/(access)/users': typeof AppSettingsaccessUsersRoute
  '/_app/_sales/companies/': typeof AppSalesCompaniesIndexRoute
  '/_app/_sales/contacts/': typeof AppSalesContactsIndexRoute
  '/_app/_sales/deals/': typeof AppSalesDealsIndexRoute
  '/_app/_sales/leads/': typeof AppSalesLeadsIndexRoute
  '/_app/_sales/notes/': typeof AppSalesNotesIndexRoute
  '/_app/developer/design-system/': typeof AppDeveloperDesignSystemIndexRoute
  '/_app/developer/design-system/components/$componentId': typeof AppDeveloperDesignSystemComponentsComponentIdRouteRoute
  '/_app/developer/design-system/patterns/object-table': typeof AppDeveloperDesignSystemPatternsObjectTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/health'
    | '/sign-in'
    | '/sign-out'
    | '/developer'
    | '/settings'
    | '/api/description'
    | '/api/mcp'
    | '/api/openapi'
    | '/auth/local-session'
    | '/companies'
    | '/contacts'
    | '/deals'
    | '/leads'
    | '/notes'
    | '/developer/design-system'
    | '/line-items'
    | '/developer/api'
    | '/developer/mcp'
    | '/developer/model'
    | '/developer/sdk'
    | '/settings/appearance'
    | '/settings/profile'
    | '/api/v1/$'
    | '/developer/'
    | '/settings/'
    | '/companies/$recordId'
    | '/contacts/$recordId'
    | '/deals/$recordId'
    | '/leads/$recordId'
    | '/notes/$recordId'
    | '/developer/design-system/foundations'
    | '/settings/group-memberships'
    | '/settings/groups'
    | '/settings/role-assignments'
    | '/settings/roles'
    | '/settings/service-accounts'
    | '/settings/users'
    | '/companies/'
    | '/contacts/'
    | '/deals/'
    | '/leads/'
    | '/notes/'
    | '/developer/design-system/'
    | '/developer/design-system/components/$componentId'
    | '/developer/design-system/patterns/object-table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/access-denied'
    | '/health'
    | '/sign-in'
    | '/sign-out'
    | '/'
    | '/api/description'
    | '/api/mcp'
    | '/api/openapi'
    | '/auth/local-session'
    | '/line-items'
    | '/developer/api'
    | '/developer/mcp'
    | '/developer/model'
    | '/developer/sdk'
    | '/settings/appearance'
    | '/settings/profile'
    | '/api/v1/$'
    | '/developer'
    | '/settings'
    | '/companies/$recordId'
    | '/contacts/$recordId'
    | '/deals/$recordId'
    | '/leads/$recordId'
    | '/notes/$recordId'
    | '/developer/design-system/foundations'
    | '/settings/group-memberships'
    | '/settings/groups'
    | '/settings/role-assignments'
    | '/settings/roles'
    | '/settings/service-accounts'
    | '/settings/users'
    | '/companies'
    | '/contacts'
    | '/deals'
    | '/leads'
    | '/notes'
    | '/developer/design-system'
    | '/developer/design-system/components/$componentId'
    | '/developer/design-system/patterns/object-table'
  id:
    | '__root__'
    | '/_app'
    | '/access-denied'
    | '/health'
    | '/sign-in'
    | '/sign-out'
    | '/_app/_sales'
    | '/_app/developer'
    | '/_app/settings'
    | '/api/description'
    | '/api/mcp'
    | '/api/openapi'
    | '/auth/local-session'
    | '/_app/'
    | '/_app/_sales/companies'
    | '/_app/_sales/contacts'
    | '/_app/_sales/deals'
    | '/_app/_sales/leads'
    | '/_app/_sales/notes'
    | '/_app/developer/design-system'
    | '/_app/_sales/line-items'
    | '/_app/developer/api'
    | '/_app/developer/mcp'
    | '/_app/developer/model'
    | '/_app/developer/sdk'
    | '/_app/settings/appearance'
    | '/_app/settings/profile'
    | '/api/v1/$'
    | '/_app/developer/'
    | '/_app/settings/'
    | '/_app/_sales/companies/$recordId'
    | '/_app/_sales/contacts/$recordId'
    | '/_app/_sales/deals/$recordId'
    | '/_app/_sales/leads/$recordId'
    | '/_app/_sales/notes/$recordId'
    | '/_app/developer/design-system/foundations'
    | '/_app/settings/(access)/group-memberships'
    | '/_app/settings/(access)/groups'
    | '/_app/settings/(access)/role-assignments'
    | '/_app/settings/(access)/roles'
    | '/_app/settings/(access)/service-accounts'
    | '/_app/settings/(access)/users'
    | '/_app/_sales/companies/'
    | '/_app/_sales/contacts/'
    | '/_app/_sales/deals/'
    | '/_app/_sales/leads/'
    | '/_app/_sales/notes/'
    | '/_app/developer/design-system/'
    | '/_app/developer/design-system/components/$componentId'
    | '/_app/developer/design-system/patterns/object-table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  HealthRoute: typeof HealthRoute
  SignInRoute: typeof SignInRoute
  SignOutRoute: typeof SignOutRoute
  ApiDescriptionRoute: typeof ApiDescriptionRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiOpenapiRoute: typeof ApiOpenapiRoute
  AuthLocalSessionRoute: typeof AuthLocalSessionRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-out': {
      id: '/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof SignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/local-session': {
      id: '/auth/local-session'
      path: '/auth/local-session'
      fullPath: '/auth/local-session'
      preLoaderRoute: typeof AuthLocalSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi': {
      id: '/api/openapi'
      path: '/api/openapi'
      fullPath: '/api/openapi'
      preLoaderRoute: typeof ApiOpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/description': {
      id: '/api/description'
      path: '/api/description'
      fullPath: '/api/description'
      preLoaderRoute: typeof ApiDescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/developer': {
      id: '/_app/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof AppDeveloperRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_sales': {
      id: '/_app/_sales'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppSalesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/developer/': {
      id: '/_app/developer/'
      path: '/'
      fullPath: '/developer/'
      preLoaderRoute: typeof AppDeveloperIndexRouteImport
      parentRoute: typeof AppDeveloperRouteRoute
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/appearance': {
      id: '/_app/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/developer/sdk': {
      id: '/_app/developer/sdk'
      path: '/sdk'
      fullPath: '/developer/sdk'
      preLoaderRoute: typeof AppDeveloperSdkRouteImport
      parentRoute: typeof AppDeveloperRouteRoute
    }
    '/_app/developer/model': {
      id: '/_app/developer/model'
      path: '/model'
      fullPath: '/developer/model'
      preLoaderRoute: typeof AppDeveloperModelRouteImport
      parentRoute: typeof AppDeveloperRouteRoute
    }
    '/_app/developer/mcp': {
      id: '/_app/developer/mcp'
      path: '/mcp'
      fullPath: '/developer/mcp'
      preLoaderRoute: typeof AppDeveloperMcpRouteImport
      parentRoute: typeof AppDeveloperRouteRoute
    }
    '/_app/developer/api': {
      id: '/_app/developer/api'
      path: '/api'
      fullPath: '/developer/api'
      preLoaderRoute: typeof AppDeveloperApiRouteImport
      parentRoute: typeof AppDeveloperRouteRoute
    }
    '/_app/_sales/line-items': {
      id: '/_app/_sales/line-items'
      path: '/line-items'
      fullPath: '/line-items'
      preLoaderRoute: typeof AppSalesLineItemsRouteImport
      parentRoute: typeof AppSalesRouteRoute
    }
    '/_app/developer/design-system': {
      id: '/_app/developer/design-system'
      path: '/design-system'
      fullPath: '/developer/design-system'
      preLoaderRoute: typeof AppDeveloperDesignSystemRouteRouteImport
      parentRoute: typeof AppDeveloperRouteRoute
    }
    '/_app/_sales/notes': {
      id: '/_app/_sales/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppSalesNotesRouteRouteImport
      parentRoute: typeof AppSalesRouteRoute
    }
    '/_app/_sales/leads': {
      id: '/_app/_sales/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppSalesLeadsRouteRouteImport
      parentRoute: typeof AppSalesRouteRoute
    }
    '/_app/_sales/deals': {
      id: '/_app/_sales/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AppSalesDealsRouteRouteImport
      parentRoute: typeof AppSalesRouteRoute
    }
    '/_app/_sales/contacts': {
      id: '/_app/_sales/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppSalesContactsRouteRouteImport
      parentRoute: typeof AppSalesRouteRoute
    }
    '/_app/_sales/companies': {
      id: '/_app/_sales/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AppSalesCompaniesRouteRouteImport
      parentRoute: typeof AppSalesRouteRoute
    }
    '/_app/developer/design-system/': {
      id: '/_app/developer/design-system/'
      path: '/'
      fullPath: '/developer/design-system/'
      preLoaderRoute: typeof AppDeveloperDesignSystemIndexRouteImport
      parentRoute: typeof AppDeveloperDesignSystemRouteRoute
    }
    '/_app/_sales/notes/': {
      id: '/_app/_sales/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof AppSalesNotesIndexRouteImport
      parentRoute: typeof AppSalesNotesRouteRoute
    }
    '/_app/_sales/leads/': {
      id: '/_app/_sales/leads/'
      path: '/'
      fullPath: '/leads/'
      preLoaderRoute: typeof AppSalesLeadsIndexRouteImport
      parentRoute: typeof AppSalesLeadsRouteRoute
    }
    '/_app/_sales/deals/': {
      id: '/_app/_sales/deals/'
      path: '/'
      fullPath: '/deals/'
      preLoaderRoute: typeof AppSalesDealsIndexRouteImport
      parentRoute: typeof AppSalesDealsRouteRoute
    }
    '/_app/_sales/contacts/': {
      id: '/_app/_sales/contacts/'
      path: '/'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AppSalesContactsIndexRouteImport
      parentRoute: typeof AppSalesContactsRouteRoute
    }
    '/_app/_sales/companies/': {
      id: '/_app/_sales/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof AppSalesCompaniesIndexRouteImport
      parentRoute: typeof AppSalesCompaniesRouteRoute
    }
    '/_app/settings/(access)/users': {
      id: '/_app/settings/(access)/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsaccessUsersRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/(access)/service-accounts': {
      id: '/_app/settings/(access)/service-accounts'
      path: '/service-accounts'
      fullPath: '/settings/service-accounts'
      preLoaderRoute: typeof AppSettingsaccessServiceAccountsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/(access)/roles': {
      id: '/_app/settings/(access)/roles'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AppSettingsaccessRolesRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/(access)/role-assignments': {
      id: '/_app/settings/(access)/role-assignments'
      path: '/role-assignments'
      fullPath: '/settings/role-assignments'
      preLoaderRoute: typeof AppSettingsaccessRoleAssignmentsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/(access)/groups': {
      id: '/_app/settings/(access)/groups'
      path: '/groups'
      fullPath: '/settings/groups'
      preLoaderRoute: typeof AppSettingsaccessGroupsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/(access)/group-memberships': {
      id: '/_app/settings/(access)/group-memberships'
      path: '/group-memberships'
      fullPath: '/settings/group-memberships'
      preLoaderRoute: typeof AppSettingsaccessGroupMembershipsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/developer/design-system/foundations': {
      id: '/_app/developer/design-system/foundations'
      path: '/foundations'
      fullPath: '/developer/design-system/foundations'
      preLoaderRoute: typeof AppDeveloperDesignSystemFoundationsRouteImport
      parentRoute: typeof AppDeveloperDesignSystemRouteRoute
    }
    '/_app/_sales/notes/$recordId': {
      id: '/_app/_sales/notes/$recordId'
      path: '/$recordId'
      fullPath: '/notes/$recordId'
      preLoaderRoute: typeof AppSalesNotesRecordIdRouteImport
      parentRoute: typeof AppSalesNotesRouteRoute
    }
    '/_app/_sales/leads/$recordId': {
      id: '/_app/_sales/leads/$recordId'
      path: '/$recordId'
      fullPath: '/leads/$recordId'
      preLoaderRoute: typeof AppSalesLeadsRecordIdRouteImport
      parentRoute: typeof AppSalesLeadsRouteRoute
    }
    '/_app/_sales/deals/$recordId': {
      id: '/_app/_sales/deals/$recordId'
      path: '/$recordId'
      fullPath: '/deals/$recordId'
      preLoaderRoute: typeof AppSalesDealsRecordIdRouteImport
      parentRoute: typeof AppSalesDealsRouteRoute
    }
    '/_app/_sales/contacts/$recordId': {
      id: '/_app/_sales/contacts/$recordId'
      path: '/$recordId'
      fullPath: '/contacts/$recordId'
      preLoaderRoute: typeof AppSalesContactsRecordIdRouteImport
      parentRoute: typeof AppSalesContactsRouteRoute
    }
    '/_app/_sales/companies/$recordId': {
      id: '/_app/_sales/companies/$recordId'
      path: '/$recordId'
      fullPath: '/companies/$recordId'
      preLoaderRoute: typeof AppSalesCompaniesRecordIdRouteImport
      parentRoute: typeof AppSalesCompaniesRouteRoute
    }
    '/_app/developer/design-system/patterns/object-table': {
      id: '/_app/developer/design-system/patterns/object-table'
      path: '/patterns/object-table'
      fullPath: '/developer/design-system/patterns/object-table'
      preLoaderRoute: typeof AppDeveloperDesignSystemPatternsObjectTableRouteImport
      parentRoute: typeof AppDeveloperDesignSystemRouteRoute
    }
    '/_app/developer/design-system/components/$componentId': {
      id: '/_app/developer/design-system/components/$componentId'
      path: '/components/$componentId'
      fullPath: '/developer/design-system/components/$componentId'
      preLoaderRoute: typeof AppDeveloperDesignSystemComponentsComponentIdRouteRouteImport
      parentRoute: typeof AppDeveloperDesignSystemRouteRoute
    }
  }
}

interface AppSalesCompaniesRouteRouteChildren {
  AppSalesCompaniesRecordIdRoute: typeof AppSalesCompaniesRecordIdRoute
  AppSalesCompaniesIndexRoute: typeof AppSalesCompaniesIndexRoute
}

const AppSalesCompaniesRouteRouteChildren: AppSalesCompaniesRouteRouteChildren =
  {
    AppSalesCompaniesRecordIdRoute: AppSalesCompaniesRecordIdRoute,
    AppSalesCompaniesIndexRoute: AppSalesCompaniesIndexRoute,
  }

const AppSalesCompaniesRouteRouteWithChildren =
  AppSalesCompaniesRouteRoute._addFileChildren(
    AppSalesCompaniesRouteRouteChildren,
  )

interface AppSalesContactsRouteRouteChildren {
  AppSalesContactsRecordIdRoute: typeof AppSalesContactsRecordIdRoute
  AppSalesContactsIndexRoute: typeof AppSalesContactsIndexRoute
}

const AppSalesContactsRouteRouteChildren: AppSalesContactsRouteRouteChildren = {
  AppSalesContactsRecordIdRoute: AppSalesContactsRecordIdRoute,
  AppSalesContactsIndexRoute: AppSalesContactsIndexRoute,
}

const AppSalesContactsRouteRouteWithChildren =
  AppSalesContactsRouteRoute._addFileChildren(
    AppSalesContactsRouteRouteChildren,
  )

interface AppSalesDealsRouteRouteChildren {
  AppSalesDealsRecordIdRoute: typeof AppSalesDealsRecordIdRoute
  AppSalesDealsIndexRoute: typeof AppSalesDealsIndexRoute
}

const AppSalesDealsRouteRouteChildren: AppSalesDealsRouteRouteChildren = {
  AppSalesDealsRecordIdRoute: AppSalesDealsRecordIdRoute,
  AppSalesDealsIndexRoute: AppSalesDealsIndexRoute,
}

const AppSalesDealsRouteRouteWithChildren =
  AppSalesDealsRouteRoute._addFileChildren(AppSalesDealsRouteRouteChildren)

interface AppSalesLeadsRouteRouteChildren {
  AppSalesLeadsRecordIdRoute: typeof AppSalesLeadsRecordIdRoute
  AppSalesLeadsIndexRoute: typeof AppSalesLeadsIndexRoute
}

const AppSalesLeadsRouteRouteChildren: AppSalesLeadsRouteRouteChildren = {
  AppSalesLeadsRecordIdRoute: AppSalesLeadsRecordIdRoute,
  AppSalesLeadsIndexRoute: AppSalesLeadsIndexRoute,
}

const AppSalesLeadsRouteRouteWithChildren =
  AppSalesLeadsRouteRoute._addFileChildren(AppSalesLeadsRouteRouteChildren)

interface AppSalesNotesRouteRouteChildren {
  AppSalesNotesRecordIdRoute: typeof AppSalesNotesRecordIdRoute
  AppSalesNotesIndexRoute: typeof AppSalesNotesIndexRoute
}

const AppSalesNotesRouteRouteChildren: AppSalesNotesRouteRouteChildren = {
  AppSalesNotesRecordIdRoute: AppSalesNotesRecordIdRoute,
  AppSalesNotesIndexRoute: AppSalesNotesIndexRoute,
}

const AppSalesNotesRouteRouteWithChildren =
  AppSalesNotesRouteRoute._addFileChildren(AppSalesNotesRouteRouteChildren)

interface AppSalesRouteRouteChildren {
  AppSalesCompaniesRouteRoute: typeof AppSalesCompaniesRouteRouteWithChildren
  AppSalesContactsRouteRoute: typeof AppSalesContactsRouteRouteWithChildren
  AppSalesDealsRouteRoute: typeof AppSalesDealsRouteRouteWithChildren
  AppSalesLeadsRouteRoute: typeof AppSalesLeadsRouteRouteWithChildren
  AppSalesNotesRouteRoute: typeof AppSalesNotesRouteRouteWithChildren
  AppSalesLineItemsRoute: typeof AppSalesLineItemsRoute
}

const AppSalesRouteRouteChildren: AppSalesRouteRouteChildren = {
  AppSalesCompaniesRouteRoute: AppSalesCompaniesRouteRouteWithChildren,
  AppSalesContactsRouteRoute: AppSalesContactsRouteRouteWithChildren,
  AppSalesDealsRouteRoute: AppSalesDealsRouteRouteWithChildren,
  AppSalesLeadsRouteRoute: AppSalesLeadsRouteRouteWithChildren,
  AppSalesNotesRouteRoute: AppSalesNotesRouteRouteWithChildren,
  AppSalesLineItemsRoute: AppSalesLineItemsRoute,
}

const AppSalesRouteRouteWithChildren = AppSalesRouteRoute._addFileChildren(
  AppSalesRouteRouteChildren,
)

interface AppDeveloperDesignSystemRouteRouteChildren {
  AppDeveloperDesignSystemFoundationsRoute: typeof AppDeveloperDesignSystemFoundationsRoute
  AppDeveloperDesignSystemIndexRoute: typeof AppDeveloperDesignSystemIndexRoute
  AppDeveloperDesignSystemComponentsComponentIdRouteRoute: typeof AppDeveloperDesignSystemComponentsComponentIdRouteRoute
  AppDeveloperDesignSystemPatternsObjectTableRoute: typeof AppDeveloperDesignSystemPatternsObjectTableRoute
}

const AppDeveloperDesignSystemRouteRouteChildren: AppDeveloperDesignSystemRouteRouteChildren =
  {
    AppDeveloperDesignSystemFoundationsRoute:
      AppDeveloperDesignSystemFoundationsRoute,
    AppDeveloperDesignSystemIndexRoute: AppDeveloperDesignSystemIndexRoute,
    AppDeveloperDesignSystemComponentsComponentIdRouteRoute:
      AppDeveloperDesignSystemComponentsComponentIdRouteRoute,
    AppDeveloperDesignSystemPatternsObjectTableRoute:
      AppDeveloperDesignSystemPatternsObjectTableRoute,
  }

const AppDeveloperDesignSystemRouteRouteWithChildren =
  AppDeveloperDesignSystemRouteRoute._addFileChildren(
    AppDeveloperDesignSystemRouteRouteChildren,
  )

interface AppDeveloperRouteRouteChildren {
  AppDeveloperDesignSystemRouteRoute: typeof AppDeveloperDesignSystemRouteRouteWithChildren
  AppDeveloperApiRoute: typeof AppDeveloperApiRoute
  AppDeveloperMcpRoute: typeof AppDeveloperMcpRoute
  AppDeveloperModelRoute: typeof AppDeveloperModelRoute
  AppDeveloperSdkRoute: typeof AppDeveloperSdkRoute
  AppDeveloperIndexRoute: typeof AppDeveloperIndexRoute
}

const AppDeveloperRouteRouteChildren: AppDeveloperRouteRouteChildren = {
  AppDeveloperDesignSystemRouteRoute:
    AppDeveloperDesignSystemRouteRouteWithChildren,
  AppDeveloperApiRoute: AppDeveloperApiRoute,
  AppDeveloperMcpRoute: AppDeveloperMcpRoute,
  AppDeveloperModelRoute: AppDeveloperModelRoute,
  AppDeveloperSdkRoute: AppDeveloperSdkRoute,
  AppDeveloperIndexRoute: AppDeveloperIndexRoute,
}

const AppDeveloperRouteRouteWithChildren =
  AppDeveloperRouteRoute._addFileChildren(AppDeveloperRouteRouteChildren)

interface AppSettingsRouteRouteChildren {
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSettingsaccessGroupMembershipsRoute: typeof AppSettingsaccessGroupMembershipsRoute
  AppSettingsaccessGroupsRoute: typeof AppSettingsaccessGroupsRoute
  AppSettingsaccessRoleAssignmentsRoute: typeof AppSettingsaccessRoleAssignmentsRoute
  AppSettingsaccessRolesRoute: typeof AppSettingsaccessRolesRoute
  AppSettingsaccessServiceAccountsRoute: typeof AppSettingsaccessServiceAccountsRoute
  AppSettingsaccessUsersRoute: typeof AppSettingsaccessUsersRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSettingsaccessGroupMembershipsRoute:
    AppSettingsaccessGroupMembershipsRoute,
  AppSettingsaccessGroupsRoute: AppSettingsaccessGroupsRoute,
  AppSettingsaccessRoleAssignmentsRoute: AppSettingsaccessRoleAssignmentsRoute,
  AppSettingsaccessRolesRoute: AppSettingsaccessRolesRoute,
  AppSettingsaccessServiceAccountsRoute: AppSettingsaccessServiceAccountsRoute,
  AppSettingsaccessUsersRoute: AppSettingsaccessUsersRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppSalesRouteRoute: typeof AppSalesRouteRouteWithChildren
  AppDeveloperRouteRoute: typeof AppDeveloperRouteRouteWithChildren
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSalesRouteRoute: AppSalesRouteRouteWithChildren,
  AppDeveloperRouteRoute: AppDeveloperRouteRouteWithChildren,
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  HealthRoute: HealthRoute,
  SignInRoute: SignInRoute,
  SignOutRoute: SignOutRoute,
  ApiDescriptionRoute: ApiDescriptionRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiOpenapiRoute: ApiOpenapiRoute,
  AuthLocalSessionRoute: AuthLocalSessionRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
